### ISSUE TITLE
pseudo growth truth depth maps?

### ISSUE THREAD

**Issue by yanre-hyd** [anantarb/triplanenet#13]
Hello author, I am curious if there is an image in your paper that should be pseudo growth truth depth maps? How should this be generated?
![depth](https://github.com/user-attachments/assets/f2992b16-c134-4d04-a8b0-5b7763b0744f)

**Comment by anantarb** [comment]
We captured multi-view video of a person asked to stand still. We then used SFM software (https://www.agisoft.com) to get the ground truth geometry.

**Comment by yanre-hyd** [comment]
thank you very much！
