### ISSUE TITLE
Encoder version for rebalanced EG3D?

### ISSUE THREAD

**Issue by luchaoqi** [anantarb/triplanenet#4]
Hi, thanks for this awesome work!
I assume the current encoder is for the original EG3D. I am wondering if you have the encoder version for [rebalanced EG3D](https://github.com/NVlabs/eg3d/blob/main/docs/models.md#ffhq-rebalanced)?

I am asking since I find the synthesis results are pretty different for the original vs. rebalanced version.
I have attached an example output of the original EG3D vs. rebalanced EG3D given the same latent code (encoded from your encoder):
original:
![image](https://github.com/anantarb/triplanenet/assets/46330265/6b187d26-e0d6-4f2c-ad80-75d78d506c54)
rebalanced:
![image](https://github.com/anantarb/triplanenet/assets/46330265/b4479d1f-f01b-425e-b3ad-c7b7f8a8cfd6)

**Comment by anantarb** [comment]
Hello, the encoder checkpoint trained on the rebalanced EG3D is available by this link: https://drive.google.com/drive/folders/1sUkTc9E1Pb0wGg138rfKIBnTJ6EIkdCo

Please download the checkpoint and save it locally as the link will be available for a short time only due to space constraint.

**Comment by luchaoqi** [comment]
Thanks!
