### ISSUE TITLE
psp_encoder

### ISSUE THREAD

**Issue by Florian-Barthel** [anantarb/triplanenet#5]
Hi,

I'm currently trying to run inference with my own custom data and I have an issue with the function `TriPlaneNet.__get_initial_inversion(self, x, camera_params, resize=True)`

I use a batch size of 1, however, the `GradualStyleEncoder` returns 4 latent vectors (`shape: (4, 14, 512)`). Then, the `TriPlaneNet.decoder.synthesis` is called with 4 latent vectors and only 1 camera parameter. This crashes, since the synthesis function expects the same amount of camera parameters as latent vectors. 

Why does TriPlaneNet.psp_encoder(x)  return 4 latent codes? And do I have to aggregate it somehow? Like the sum or the average?

Thanks in advance!

**Comment by anantarb** [comment]
Hello,

Could you please check the size of "x" that is passed to `TriPlaneNet.__get_initial_inversion(self, x, camera_params, resize=True)`? It must be (4, _, _, _) where 4 is the batch dimension. If that's the case, maybe the dataloader is loading the batch incorrectly.

Regarding the latent codes, the function should return 1 latent code not 4 if you are passing a single image. And, you do not have to aggregate anything.

**Comment by Florian-Barthel** [comment]
Hi,

thanks for your quick response!

I was passing x with shape (1, 3, 512, 512) and the `self.psp_encoder(x)` returned a result with shape (4, 14, 512). I, however, found my mistake. As the psp_encoder was expecting data of size 256x256, which is 4 times fewer than 512x512, I somehow ended up with batch-size 4. I downsampled the images before calling `self.psp_encoder(x)` and now it works.
