### ISSUE TITLE
Runtime Error: The expanded size of the tensor

### ISSUE THREAD

**Issue by artificialnouveau** [anantarb/triplanenet#9]
When I run the following code:

`python scripts/inference_v2.py --exp_dir=experiment --checkpoint_path=triplanenet_v2_final.pth --data_path=dataset_preprocessing/ffhq/example_dataset --test_batch_size=4 --test_workers=4 --shapes --novel_view_angles -0.3 0.3
`

I get the following error:

```
Error occurred: ./models/mtcnn/mtcnn_pytorch/src/align_trans.py:287: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if align_type is 'cv2_affine':
./models/mtcnn/mtcnn_pytorch/src/align_trans.py:290: SyntaxWarning: "is" with a literal. Did you mean "=="?
  elif align_type is 'affine':
  0%|          | 0/1 [00:55<?, ?it/s]
Traceback (most recent call last):
  File "scripts/inference_v2.py", line 178, in <module>
    run()
  File "scripts/inference_v2.py", line 88, in run
    results_batch, depth_batch, sigmas = run_on_batch(x, x_mirror, camera_param, camera_param_mirror, net, opts, fname)
  File "scripts/inference_v2.py", line 167, in run_on_batch
    novel_view_camera_params[:, :16] = cam2world_pose.view(cam2world_pose.size(0), -1)
RuntimeError: The expanded size of the tensor (1) must match the existing size (4) at non-singleton dimension 0.  Target sizes: [1, 16].  Tensor sizes: [4, 16]

```

I've downloaded triplanenet_v2_final.pth, model_ir_s350.pth, ffhq512-128.pth, epoch_20.pth, Exp_Pca.bin, mtcnn.tar.gz, discriminator.pth, and CurricularFace_Backbone.pth. 

Do you what could be causing the issue?

Thank you for all the work that you've done! Highly appreciate it.

**Comment by anantarb** [comment]
Hello, Can you try by setting --test_batch_size=1? Since there is a single image in the dataset_preprocessing/ffhq/example_dataset/ directory, maybe setting --test_batch_size=4 didn't work here.

**Comment by artificialnouveau** [comment]
Perfect, yes that was the issue
